var main_trials = [
	{focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 0,
     otherShape: "square",
     size: 30,
     total: 10,
     rows: 3
    },
    {focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 5,
     otherShape: "circle",
     size: 30,
     total: 10,
     rows: 8
    },
    {focalColor: "red",
     otherColor: "red",
     focalShape: "square",
     focalNumber: 20,
     otherShape: "triangle",
     size: 16,
     total: 50,
     rows: 2
    },
    {focalColor: "blue",
     otherColor: "red",
     focalShape: "circle",
     focalNumber: 8,
     otherShape: "circle",
     size: 30,
     total: 10,
     rows: 4
    },
    {focalColor: "green",
     otherColor: "red",
     focalShape: "square",
     focalNumber: 1,
     otherShape: "circle",
     size: 30,
     total: 5,
     rows: 1
    }
];